services:
  ssh-honeypot:
    build: ./honeypots/ssh-hp
    container_name: ssh-honeypot
    ports:
      - "2222:22"
    restart: always
    volumes:
      - ./ttylogs:/var/log/tty
  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ./mongodata:/data/db

  ssh-parser:
    build: ./ssh-parser
    container_name: ssh-parser
    restart: always
    depends_on:
      - ssh-honeypot
      - mongo
    volumes:
      - ./ttylogs:/data/ttylogs
      - ./rawlogs:/data/raw
      - ./jsonlogs:/data/json
    environment:
      - MONGO_URI=mongodb://mongo:27017/ttylogs
      - SCAN_INTERVAL=10

  backend:
    build: ./backend
    container_name: backend
    restart: always
    volumes:
      - ./backend:/app
      - /app/node_modules # Use an anonymous volume to prevent host node_modules from overwriting container's
    depends_on:
      - mongo
    # Pass environment variables from a .env file in your backend directory
    env_file:
      - ./backend/.env
    environment:
      - MONGO_URI=mongodb://mongo:27017/ttylogs
    command: npm run dev
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"

