version: '3.9'

services:
  modbus-honeypot:
    build: .
    container_name: modbus_honeypot
    ports:
      - "502:502"
    volumes:
    - ./registers.json:/app/registers.json
    - ./logs:/app/logs
    restart: unless-stopped
    cap_add:
      - NET_BIND_SERVICE  # Allow binding to port 502
